# Generated by Django 2.2.14 on 2020-12-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
